#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Quotes collection
#+date: <2021-05-01 Sat>
#+author: Nasser Alkmim
#+email: nasser.alkmim@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.2 (Org mode 9.4.5)
#+draft: t
#+tags[]: favorites quotes essays
#+toc: t
* Feynman - Note taking

#+begin_quote
Weiner: Well, the work was done in your head but the record of it is still here.
Feynman: No, it’s not a record, not really, it’s working. You have to work on paper and this is the paper. OK?
#+end_quote

Weiner assumes that the notes are just a record of the ``work'' that Feynman did.
Feynman corrects him saying that it not a ``record'' but the ``work'' itself.
He says ``It's the doing it''.
Note taking is not a mere record of the thinking process but the think process itself.

* Stroustrup - Learning analogy

#+begin_quote
To get into the air, a plane has to accelerate along the runway until
it moves fast enough to “jump” into the air. While the plane is
lumbering along the runway, it is little more than a particularly
heavy and awkward truck. Once in the air, it soars to become an
altogether different, elegant, and efficient vehicle. It is in its
true element. -- Stroustrup
#+end_quote

Momentum specially during beginning phases.
The initial learning struggle.

* Musashi - Desires and failures

#+begin_quote
There is nothing outside of yourself that can ever enable you to get better, stronger, richer, quicker, or smarter. Everything is within. Everything exists. Seek nothing outside of yourself. -- Miyamoto Musashi, The Book of Five Rings
#+end_quote

Musashi gives an advice about our desires.
How desires can lead to frustration when they are unachievable.
Seek nothing outside of yourself is a self defense mechanism.

* No comments

Discipline is doing something you hate and loving it. Mike Tyson

The notes you play are the notes you don't play. Miles Davis

The best is the enemy of the good. Voltaire

The purpose of life is to find the largest burden that you can bear and bearing it. Jordan Peterson

Analogy-making is the machinery behind the pulsating heartbeat of thought: categorization. Hofstadter

When you wish to instruct, be brief. Cicero

Jump in and see if you can swim. Bill gore

I've made this letter longer than usual because I lack the time to make it short. Pascal

Success is not final, failure is not fatal: it is the courage to continue that counts.” — Winston Churchill

As a young man, life was for him a search for meaning; as an adult an appreciation of beauty; and as a mature man a source of joy. Fisher Black daughter.

Everyone is dealt a hand of cards, some get good cards others less good. However, you are not the cards, you are the player. How you play the cards is what defines the outcomes. Tech lead analogy.

All of humanity problems stems from man's inability to sit quietly in a room alone. Pascal.

Love can not express the idea of music, while music may give an idea of love. Berlioz.

Quando escuto Mahler não estou escutando apenas música mas sim escutando alguém que compreendeu a vida.

Beautiful and imaginative things can be destroyed, asthetic (beauty and imagination) can not. Alan moore.

You failed when you let others defined your success. Tech lead.

You never know how strong you are until been strong is your only option. Bob Marley

There is nothing irrational in something that does not harm you. Taleb plestra 2017 em Rutgers Univ.

Não importa a nota errada e sim a próxima nota. Miles Davis

The fool is the percursor to the sábio, Carl Young.

Sonhar com vidas que não tive. Fabrício Corsaletti

Logic of Risk Taking”, SITG, Taleb, 2018. I believe t  hat risk aversion does not exist: what we observe is, simply, a residual of ergodicity. People are, simply, trying to avoid financial suicide and take a certain attitude to tail risks.”

Greatness inspires greatness

Um característica de pessoas interessantes são aquelas que persistiram desbravando algum caminho na ignorância. Aprender  instrumento na pira intuição e injenuidade, não sabe a teoria mas descobriu com a prática inssessante a lógica s formalismo. Só a injenuidade pura permite as pessoas persistirem em tal caminho. Nasser

Financial crises all pretty much have the form of bank runs: Long-term assets are funded using short-term liabilities, those short-term liabilities come due and can’t be rolled over due to panic, and the result is fire sales and further panic. The way to stop a financial crisis is to step in and lend when no one else will, and so that’s what the Fed will do, for pretty much anything you’ve got.

When gambling, think probability. When hedging, think plausibility. When preparing, think possibility. Hary crane

Aristotles, it is the mark of an educated mind to entertain a thought without accepting it.

[Note 1: My Stand Againt Atheism. This, and many other things explain why I just cannot understand atheism. I just cannot. If I were to take “rationality” to its limit, I would then have to treat the dead no differently from the unborn, those who came and left us in the same manner as those who do not exist yet. Otherwise I would be making the mistake of sunk costs [endowment effect]. I cannot & I just do not want to. Homo sum! I want to stay rational in the profane, not the sacred.] Taleb

It is becoming impossible for me to think about randomness without thinking about aesthetics; so I am thinking about aesthetics and nothing else. Geometrically-tractable randomness cannot be separated from aesthetics ( think order and beauty v/s disorder; without some notion of randomness one cannot grasp disorder). Platonic randomness is at the core of aesthetics (so is behaving with elegance for elegance’s sake; more on behavioral aesthetics later...) I wonder if entropy is not too primitive a designation. Taleb

My “Greek Levantine” character puts “poetry before prose, Greeks before Romans, dignity before elegance, elegance before culture, culture before erudition, erudition before knowledge, knowledge before intellect, and intellect before results”. Taleb

George Spencer Brown has famously said about Sir Isaac Newton that  “to arrive at the simplest truth, as Newton knew and practiced, requires years of contemplation. Not activity. Not reasoning. Not calculating.  Not busy behavior of any kind. Not reading. Not talking. Not making an effort. Not thinking. Simply bearing in mind what it is that one needs to know.”

Ethics = aesthetics ambas formas de valores. Ética é o ramo da filosofia que estuda como o homem deve agir dado a natureza da realidade (metafísica) a como o homem conhece a realidade (epistemologia). Aesthetics e a recriação seletiva da realidade. Os gregos : o belo e o bom, harmonia. Taleb

“It takes some humanity to feel sympathy for those less fortunate than us; but it takes honor to avoid envying those who are much luckier.” — Nassim Nicholas Taleb @nntaleb https://t.co/kGuWIWOSBu

"Um homem não é velho até que seus arrependimentos tomem o lugar de seus sonhos." - Provérbio iídiche

Give me 6 hours to chop a tree, I will spend the first 4 sharpening the axe. Lincoln

Decisão mais importante o que vc vai fazer hj, segunda o que você vai fazer amanhã, terceira o que você vai fazer ano que vem

Motivação falha, hábitos sucedem, força de vontade falha, planejamento sucede

He who has a why to live can bear any how. Nietzsche

Memory is the residue of thought, Daniel willingham

Be not afraid of going slowly, be only afraid of standing still. Chinese proverb

Mathematicians think in objects and relations, jurists think in constructs, logicians in maximally abstract operators and fools in words, taleb

Esse quam videri, to be rather to be seen as such

The Romans judged their political system by not asking wether it makes sense but wether it worked, Tom Holland

That make a man an offender for a word, and lay a snare for him that reproveth in the gate, and turn aside the just for a thing of nought. Isaiah 29 21

The problem is never the problem is how people handle, taleb nassim

Hire for attitude, train for skill

Os tolos dizem que aprendem pela experiência. Eu prefiro aproveitar a experiência dos outros. Bismarck

Max Planck e o motorista depois do nobel

Minha vida foi cheia de infortúnios, a maioria deles  não aconteceu. Montaigne

Trabalhar sozinho pode ser mais rápido, mas trabalhando em grupo pode se chegar mais longe

Via negativa - a remoção não causa efeitos colaterais nem gera imprevisiveis/não intencionais/não planejados reações em cadeia

Papel da religião, nos proteger do viés da intervenção (não fazer nada é melhor que fazer, as vezes)

A falta de pele em jogo é o maior fragilizador. Burocratas tomam decisões sem nenhuma consequência própria e muito dano à terceiros

Estratégia barbel, em vez de tomar ações na média, dividir em duas partes antagônica em proporção adequada.

Via negativa, em sistemas complexos é melhor agir retirando algo do que colocando, o que causa efeitos colaterais imprevisiveis e desencadeia reações não desejadas

The contact with the world is done via skin in the game. You cannot separate knowledge from the ground

Greek pathemata mathemata - guide your learning through pain

Interventionists flaws: they think in statics not Dynamics, they think in low not in high dimensions, they thinks ink actions not interactions - Talebvon interventionists

God has nothing to do with religion and religion has nothing to do with God and both has nothing to do with me

Don't live for golden handcuffs

Final fantasy 8 was the best one

O mundo quer ser enganado, Kierkegaard

Eu sou otimista, não veja utilidade nenhuma ser outra coisa, Churchill

Try and fail is very different than fail to try, Chester Bernard

All human knowledge is uncertain, inexact and partial. Bertrand Russell

The heart has its reasons which reasons knows nothing of. Blaise Pascal

It is better to be asked why there is no statue in your name than why there is one. Cato

It is possible to make no mistakes and lose. That is not failure; that is life. Cpt. Jean-Luc Picard
