#+TITLE: Monetary policy and lender of last resort
#+DATE: 2020-12-13T20:08:58-03:00
#+PUBLISHDATE: 2020-12-13T20:08:58-03:00
#+TAGS[]: economy, monetary-policy
#+DESCRIPTION: Short description
#+toc: t
#+draft: t
* Traditional MP
*** FED
FED uses its reserves (liabilities) to affect the Federal Funds Rate (FFR), short term interest rate.

If the FED reduces reserves, buying T-Bills in the open market operations, it affects the FFR upwards.

*** Money Market dealers
Money market (MM) dealers are directly affected because they borrow short (overnight) and lend in term (3 months).

If the financing cost increases, the MM dealers also push the term price upwards.

*** Security dealers
Security (SE) dealers borrow in the term market (money market, e.g. REPO) to lend in the long-tem Capital market (CM).

 It will pay less for the security, by lowering the price, the yield increases. 

 SE dealer makes market both ways, it borrows money with colateral (REPO, liability) and it lends money for colateral (reverse REPO, asset).

 The inventory of a SE dealer are securities, if the cost to finance them (MM) goes up then the dealer, who wants to make profit, will have to increase the rate of the other side of the trade.

 Ultimately the SE dealer is purchasing a security and using the security to fund itself by borrowing the MM.

 SE dealer connects someone with excess money and wants earn interest (e.g. pension fund) with someone holding a security and wants to finance it (e.g. bank), so the bank is the ultimate borrower and the pension fund is the ultimate lender and the SE is making money with the spread because it is creating the market.

* Lender of last resort

*** Why we need a lender of last resort?

* References

1. [[https://economicquestions.org/why-is-the-fed-willing-to-flatten-the-yield-curve-but-not-control-it/]]
2. Manias, panics and crashes. Kindleberger.

