#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Text processing with spaCy
#+date: <2020-12-09 Wed>
#+author: Nasser Alkmim
#+email: nasser.alkmim@gmail.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.3.7)
#+tags[]: machine-learning natural-language-processing
#+toc: t
* Introduction

spaCy is a library for Natural Language Processing (NLP) in python.
It offers multiple solutions for text processing such as tokenization, named entity recognition, word vectors, part of speech tagging.
The alternative is the library NLTK which seems to be used mostly in academia whereas spaCy is recommended for production use.


* Load the language model
We need to download the models for the language with =python -m spacy download model-name.=
Then we can load the language model in our code by creating a =Language= object.
This object has all the data and methods required to process the text.
By calling this object on a string of text we get a processed object =Doc=, which is a sequence of =Token= objects.
The =Doc= object has a =__getitem__()= method which enabled the container to be accessed like a list.



#+begin_src python
import spacy
nlp = spacy.load('pt_core_news_sm')
text = """Joaquim Maria Machado de Assis (Rio de Janeiro, 21 de junho de
1839 — Rio de Janeiro, 29 de setembro de 1908) foi um escritor
brasileiro, considerado por muitos críticos, estudiosos, escritores e
leitores um dos maiores senão o maior nome da literatura do Brasil."""
doc = nlp(text)
print(doc, type(doc))
#+end_src

#+RESULTS:
: Joaquim Maria Machado de Assis (Rio de Janeiro, 21 de junho de
: 1839 — Rio de Janeiro, 29 de setembro de 1908) foi um escritor
: brasileiro, considerado por muitos críticos, estudiosos, escritores e
: leitores um dos maiores senão o maior nome da literatura do Brasil. <class 'spacy.tokens.doc.Doc'>

* Tokenization

When the string is processed into =Doc= spaCy automatically tokenizes the text.
Which is the process of dividing the text in individual entities.

#+begin_src python
for token in doc[:10]:
    print(token.text)
#+end_src

#+RESULTS:
: Joaquim
: Maria
: Machado
: de
: Assis
: (
: Rio
: de
: Janeiro
: ,

We can see it considers already punctuation rules.

* Part of speech (POS)

Part of speech tagging is a process in which we want to know what word type our tokens are.
The model loaded was trained to be capable of associate words to its type.
We need to use =token.pos_= in order to get a readable string.

#+begin_src python
for token in doc[:10]:
    print(token.text, token.pos_)
#+end_src

#+RESULTS:
: Joaquim PROPN
: Maria PROPN
: Machado PROPN
: de ADP
: Assis PROPN
: ( PUNCT
: Rio PROPN
: de ADP
: Janeiro PROPN
: , PUNCT


we can see the types: PROPN (proper noun), ADP (adposition), PUNCT (punctuation).

spaCy offers a really neat form of displaying the text.

#+begin_src python
spacy.displacy.render(doc[:5])
#+end_src

#+RESULTS:
#+begin_export html
<span class="tex2jax_ignore"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="pt" id="4f5594799d994e6689374bbd276acd3b-0" class="displacy" width="925" height="399.5" direction="ltr" style="max-width: none; height: 399.5px; color: #000000; background: #ffffff; font-family: Arial; direction: ltr">
<text class="displacy-token" fill="currentColor" text-anchor="middle" y="309.5">
    <tspan class="displacy-word" fill="currentColor" x="50">Joaquim</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="50">PROPN</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="309.5">
    <tspan class="displacy-word" fill="currentColor" x="225">Maria</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="225">PROPN</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="309.5">
    <tspan class="displacy-word" fill="currentColor" x="400">Machado</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="400">PROPN</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="309.5">
    <tspan class="displacy-word" fill="currentColor" x="575">de</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="575">ADP</tspan>
</text>

<text class="displacy-token" fill="currentColor" text-anchor="middle" y="309.5">
    <tspan class="displacy-word" fill="currentColor" x="750">Assis</tspan>
    <tspan class="displacy-tag" dy="2em" fill="currentColor" x="750">PROPN</tspan>
</text>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-4f5594799d994e6689374bbd276acd3b-0-0" stroke-width="2px" d="M70,264.5 C70,177.0 215.0,177.0 215.0,264.5" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-4f5594799d994e6689374bbd276acd3b-0-0" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">flat:name</textPath>
    </text>
    <path class="displacy-arrowhead" d="M215.0,266.5 L223.0,254.5 207.0,254.5" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-4f5594799d994e6689374bbd276acd3b-0-1" stroke-width="2px" d="M70,264.5 C70,89.5 395.0,89.5 395.0,264.5" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-4f5594799d994e6689374bbd276acd3b-0-1" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">flat:name</textPath>
    </text>
    <path class="displacy-arrowhead" d="M395.0,266.5 L403.0,254.5 387.0,254.5" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-4f5594799d994e6689374bbd276acd3b-0-2" stroke-width="2px" d="M595,264.5 C595,177.0 740.0,177.0 740.0,264.5" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-4f5594799d994e6689374bbd276acd3b-0-2" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">case</textPath>
    </text>
    <path class="displacy-arrowhead" d="M595,266.5 L587,254.5 603,254.5" fill="currentColor"/>
</g>

<g class="displacy-arrow">
    <path class="displacy-arc" id="arrow-4f5594799d994e6689374bbd276acd3b-0-3" stroke-width="2px" d="M70,264.5 C70,2.0 750.0,2.0 750.0,264.5" fill="none" stroke="currentColor"/>
    <text dy="1.25em" style="font-size: 0.8em; letter-spacing: 1px">
        <textPath xlink:href="#arrow-4f5594799d994e6689374bbd276acd3b-0-3" class="displacy-label" startOffset="50%" side="left" fill="currentColor" text-anchor="middle">nmod</textPath>
    </text>
    <path class="displacy-arrowhead" d="M750.0,266.5 L758.0,254.5 742.0,254.5" fill="currentColor"/>
</g>
</svg></span>
#+end_export

* Named entity recognition (NER)
The NER process aims to identify entities that represent something in reality (e.g. person, city, date).
The attribute =doc.ents= are the named entities as a tuple.

#+begin_src python
for ent in doc.ents:
    print(ent.text, ent.label_)
#+end_src

#+RESULTS:
: Joaquim Maria Machado de Assis PER
: Rio de Janeiro LOC
: Rio de Janeiro LOC
: Brasil LOC

Very nice and easy.
This result can also be display nicely.

#+begin_src python
spacy.displacy.render(doc, style='ent')
#+end_src

#+RESULTS:
#+begin_export html
<span class="tex2jax_ignore"><div class="entities" style="line-height: 2.5; direction: ltr">
<mark class="entity" style="background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Joaquim Maria Machado de Assis
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">PER</span>
</mark>
 (
<mark class="entity" style="background: #ff9561; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Rio de Janeiro
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">LOC</span>
</mark>
, 21 de junho de</br>1839 — 
<mark class="entity" style="background: #ff9561; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Rio de Janeiro
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">LOC</span>
</mark>
, 29 de setembro de 1908) foi um escritor</br>brasileiro, considerado por muitos críticos, estudiosos, escritores e</br>leitores um dos maiores senão o maior nome da literatura do 
<mark class="entity" style="background: #ff9561; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Brasil
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">LOC</span>
</mark>
.</div></span>
#+end_export




As we can see, it didn't recognize the dates.
We can manually assign those.

#+begin_src python
print(doc[10:16])
from spacy.tokens import Span
date_ent = Span(doc, 10, 16, label='DATE')
doc.ents = list(doc.ents) + [date_ent] # add a new ent to the list
spacy.displacy.render(doc, style='ent')
#+end_src

#+RESULTS:
:RESULTS:
: 21 de junho de
: 1839
#+begin_export html
<span class="tex2jax_ignore"><div class="entities" style="line-height: 2.5; direction: ltr">
<mark class="entity" style="background: #ddd; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Joaquim Maria Machado de Assis
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">PER</span>
</mark>
 (
<mark class="entity" style="background: #ff9561; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Rio de Janeiro
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">LOC</span>
</mark>
, 
<mark class="entity" style="background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    21 de junho de
1839
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">DATE</span>
</mark>
 — 
<mark class="entity" style="background: #ff9561; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Rio de Janeiro
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">LOC</span>
</mark>
, 29 de setembro de 1908) foi um escritor</br>brasileiro, considerado por muitos críticos, estudiosos, escritores e</br>leitores um dos maiores senão o maior nome da literatura do 
<mark class="entity" style="background: #ff9561; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">
    Brasil
    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem">LOC</span>
</mark>
.</div></span>
#+end_export
:END:

* Conclusion

I am very impressed by this tool.
Very high level and easy to use, I'm looking forward to explore it more.

