#+title: Principles for note taking
#+date: <2020-12-21 Mon>
#+author: Nasser Alkmim
#+toc: t
#+tags[]: note-taking 
#+draft: t
* Why taking notes?
** Legendary Feynman quote
    #+begin_quote
    Weiner: Well, the work was done in your head but the record of it is still here    

    Feynman: No, it’s not a record, not really, it’s working. You have to work on paper and this is the paper. OK?

   -- Feynman Interview with Weiner
    #+end_quote

Weiner assumes that the notes are just a record of the ``work'' that Feynman did.
Feynman corrects him saying that it not a ``record'' but the ``work'' itself.
He says ``It's the doing it''.
Note taking is not a mere record of the thinking process but the think process itself.
** The why
It is simple, you want a place to refer when your memory fails.
** Benefits of note-taking?
The process of note-taking will force you to put cognitive effort into it.
This cognitive effort comes from our natural analogy making process.
(See Hofstadter book: "Surfaces and Essence")
** Clarity and thought process

* Principles for note taking
** Be consistent

Use the same letter size, grids help.
Avoid random curvy arrows, use straight ones.

** Be concise

I use what I call: layers of knowledge.
You start on the left margin with a topic.
Then, your dissect the topic from big ideas to small ideais.
This is an top-down approach with a visual guide, so when you are thinking about details you can easily look back and remember the big picture.

Notes should be in a A4 page.
If you need more space, you have two options: first you can structure your notes better by subdividing in two different notes; or, second, you can increase the page length a little bit if you think the extra information is essential and closely related to the rest.

** Drawings

If you can summarize the idea with an image, do it.
This is superior to just rephrase an idea.

* How to learn?

** Avoid hermetic information
Hermetic means isolated.

The opposite to hermetc information is relational information.

Always think relational information.

** Analogy is the core of cognition
What is cognition?
What is a concept?
What is an analogy?


** What it means to learn with the "Via Negativa"?

*** Learning and skin in the game?
Think about explaining what you learn to someone else.
The risk for you reputation is in the game.



* Workflows and heuristics
** Analogy as the core of cognition
** Start with questions and

Begin reading with questions in mind.
This will increase awareness.


Read an abstract then formulate questions to answer.
* Guidelines for writing better
** Clarity
The goal is to make the reader understand.
** How readers read?

Structure influences interpretation.

Keep subject and verb close.
We look for syntactic resolution.
Verb indicates where the subject is going.
** Principles

1. Follow a grammatical subject as soon as possible with its verb.
2. Place in the stress position the "new information" you want the reader to emphasize.
3. Place the person or thing whose "story" a sentence is telling at the beginning of the sentence, in the topic position.
4. Place appropriate "old information" (material already stated in the discourse) in the topic position for linkage backward and contextualization forward.
5. Articulate the action of every clause or sentence in its verb.
6. In general, provide context for your reader before asking that reader to consider anything new.
7. In general, try to ensure that the relative emphases of the substance coincide with the relative expectations for emphasis raised by the structure.

** References

https://www.americanscientist.org/blog/the-long-view/the-science-of-scientific-writing 
